name: Auto update Julia dependencies

env:
  JULIA_VERSION: "1.7"
  JULIA_PKG_PRECOMPILE_AUTO: 0
  JULIA_NUM_THREADS: 2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every week

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Julia ${{ env.JULIA_VERSION }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VERSION }}
      - name: Update Julia dependencies
        run: julia --color=yes --project=@. -e 'import Pkg; Pkg.update()'
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          # PAT with repo access
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            automerge
